//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// CamMonitor.rc で使用
//
#define IDCANCEL2                       3
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_ERROR_FILEOPEN              101
#define IDS_REC                         102
#define IDS_RECORDING                   103
#define IDS_PLAY                        104
#define IDS_OPEN_FILTER                 105
#define IDS_PAUSE                       106
#define IDS_ALREADY_OPEN                107
#define IDS_RESTART_MSG                 107
#define IDS_ERROR_OPEN                  108
#define IDS_TEXT_ACQUISITION_MODE       108
#define IDS_DRAWTEXT_CAMERA             109
#define IDS_ERROR_CODE                  110
#define IDS_IMG_SAVE_COMPLETE           111
#define IDS_SYNC_IN_INTERNAL            111
#define IDS_STOP                        112
#define IDS_CLOSE                       113
#define IDS_SYNC_IN_EXTERNAL            114
#define IDS_DRAWTEXT_FILE               115
#define IDS_QUALITY_NORMAL              116
#define IDS_QUALITY_LOW                 117
#define IDS_QUALITY_HIGH                118
#define IDS_ERROR_OUTPUT_CSV            119
#define IDS_SAVE_CDV_FILTER             120
#define IDS_SAVE_CSV_FILTER             120
#define IDS_COMPLETED                   121
#define IDS_ERROR_SAVE_IMAGE            122
#define IDS_ERROR_SAVE                  122
#define IDS_TEXT_SINGLE                 123
#define IDS_TEXT_CONTINUOUS             124
#define IDS_TEXT_RECORD_MODE            125
#define IDS_TEXT_MEMORY                 126
#define IDS_TEXT_STORAGE                127
#define IDR_MAINFRAME                   128
#define IDS_ERROR_NOT_SUPPORTED         129
#define IDS_TEXT_RECORD_TIME            130
#define IDS_TEXT_SETUP                  131
#define IDS_TEXT_FRAMERATE              132
#define IDS_TEXT_SHUTTER_SPEED          133
#define IDS_TEXT_RESOLUTION             134
#define IDS_TEXT_ADVANCED_SETTING       135
#define IDS_TEXT_EXPOSE                 136
#define IDS_TEXT_SYNC_IN                137
#define IDS_TEXT_SYNC_OUT               138
#define IDS_TEXT_INTERNAL               139
#define IDS_TEXT_EXTERNAL               140
#define IDS_TEXT_SIGNAL                 141
#define IDS_TEXT_POSI                   142
#define IDS_TEXT_NEGA                   143
#define IDS_TEXT_DELAY                  144
#define IDS_TEXT_WIDTH                  145
#define IDS_TEXT_MAGNIFICATION          146
#define IDS_TEXT_QUANTIZATION           147
#define IDS_TEXT_DECODE_POSITON         148
#define IDS_TEXT_DECODE_MODE            149
#define IDS_TEXT_SAVE_TO                150
#define IDS_TEXT_RESET_SEQNO            151
#define IDS_TEXT_SNAPSHOT               152
#define IDS_TEXT_RECORD                 153
#define IDS_TEXT_STOP                   154
#define IDS_TEXT_OPEN_FILE              155
#define IDS_TEXT_FILE_INFO              156
#define IDS_TEXT_FILE_PATH              157
#define IDS_TEXT_FRAME_RATE             158
#define IDS_TEXT_SIZE                   159
#define IDS_TEXT_FRAME_COUNT            160
#define IDS_TEXT_PLAYBACK               161
#define IDS_TEXT_RESAVE_FORMAT          162
#define IDS_TEXT_DROP_FRAME_INTERPOLATE 163
#define IDS_TEXT_NON                    164
#define IDS_TEXT_BLACK_IMAGE            165
#define IDS_TEXT_PREFRAME_IMAGE         166
#define IDS_TEXT_SAVE                   167
#define IDS_OUTPUT_DROP_FRAMES          168
#define IDS_TEXT_SAVE_FILE              169
#define IDS_TEXT_LANGUAGE_CHANGE        170
#define IDD_CAMERA                      310
#define IDD_OPERATION                   312
#define IDD_FILE                        313
#define IDD_SELECT_CAMERA               314
#define IDD_PROGRESS                    316
#define IDD_DEVICE_SETTINGS             322
#define IDD_DIALOG1                     324
#define IDD_LIVE                        328
#define IDD_SAVE_LIVE                   331
#define IDD_SAVE_FILE                   333
#define IDC_ACQUISITION_SINGLE          1001
#define IDC_ACQUISITION_CONTINUOUS      1002
#define IDC_TAB_CTRL                    1002
#define IDC_REFERENCE                   1003
#define IDC_RECORD_MODE_MEMORY          1003
#define IDC_FILEPATH                    1004
#define IDC_SAVE_FILE_RAW               1004
#define IDC_REOCRD_MODE_STORAGE         1004
#define IDC_RECORD_MODE_STORAGE         1004
#define IDC_NEXT_FRAME                  1005
#define IDC_FORWARD_FRAME               1005
#define IDC_SAVE_FILE_MULTIPLE_RAW      1005
#define IDC_SAVE_FILE_RAW2              1005
#define IDC_SAVE_FILE_CSV               1005
#define IDC_CURRENT_FRAME               1006
#define IDC_REC                         1006
#define IDC_PLAYBACK                    1007
#define IDC_STOP                        1007
#define IDC_PLAY                        1007
#define IDC_FOLDERPATH                  1008
#define IDC_BACKWARD_FRAME              1008
#define IDC_FILENAME                    1009
#define IDC_GO_TO_START                 1009
#define IDC_FRAMERATE                   1010
#define IDC_GO_TO_END                   1010
#define IDC_START_FRAME                 1011
#define IDC_SHUTTERFPS                  1011
#define IDC_END_FRAME                   1012
#define IDC_RESOLUTION                  1012
#define IDC_OPEN                        1013
#define IDC_SYNC_OUT_DELAY              1013
#define IDC_SLIDER_PLAY                 1014
#define IDC_SYNC_OUT_WIDTH              1014
#define IDC_FRAME_COUNT                 1015
#define IDC_OPENCAMERA                  1015
#define IDC_IMAGE_SIZE                  1016
#define IDC_COMBO_CAMERA                1016
#define IDC_SYNC_OUT_MAGNIFICATION      1016
#define IDC_FILE_FRAMERATE              1017
#define IDC_EDIT_TIMEOUT                1017
#define IDC_EDIT_TRANSFER_TIMEOUT       1017
#define IDC_EDIT_SINGLE_XFER_TIMEOUT    1017
#define IDC_QUANTIZATION                1017
#define IDC_SEQ_NO                      1018
#define IDC_EDIT_STM_COUNT              1018
#define IDC_FOLDERPATH2                 1018
#define IDC_EXPOSE_ON                   1018
#define IDC_EDIT_RING_BUF_COUNT         1018
#define IDC_SPIN_TIMEOUT                1019
#define IDC_FILENAME2                   1019
#define IDC_EXPOSE_OFF                  1019
#define IDC_SPIN_TRANSFER_TIMEOUT       1019
#define IDC_SPIN_SINGLE_XFER_TIMEOUT    1019
#define IDC_SPIN_STM_COUNT              1020
#define IDC_IMG_SAVE                    1020
#define IDC_SPIN_EXPOSE_ON              1020
#define IDC_SPIN_RING_BUF_COUNT         1020
#define IDC_REFERENCE3                  1020
#define IDC_SNAPSHOT                    1020
#define IDC_EDIT_STM_RETRY              1021
#define IDC_REFERENCE2                  1021
#define IDC_SPIN_EXPOSE_OFF             1021
#define IDC_EDIT_STREAMING_TIMEOUT      1021
#define IDC_EDIT_CONTINUOUS_XFER_TIMEOUT 1021
#define IDC_CONFIGURATION               1021
#define IDC_SPIN_STM_RETRY              1022
#define IDC_SAVE_PROGRESS               1022
#define IDC_SPIN_SYNC_OUT_DELAY         1022
#define IDC_PROGRESS_BAR                1022
#define IDC_SPIN_STREAMING_TIMEOUT      1022
#define IDC_SPIN_CONTINUOUS_XFER_TIMEOUT 1022
#define IDC_POST_START_FRAME            1022
#define IDC_ANALYZE_LIVE                1022
#define IDC_PROGRESS_TEXT               1023
#define IDC_SPIN_SYNC_OUT_DELAY2        1023
#define IDC_SPIN_SYNC_OUT_WIDTH         1023
#define IDC_POST_START_FRAME2           1023
#define IDC_POST_END_FRAME              1023
#define IDC_SAVE_TO                     1023
#define IDC_DECODE_POS_X                1024
#define IDC_SAVE_FRAME_INFO             1024
#define IDC_SYNC_OUT_SIGNAL_POSI        1025
#define IDC_ANALYZE_FILE                1025
#define IDC_SYNC_OUT_SIGNAL_NEGA        1026
#define IDC_SAVE_TO_FILE                1026
#define IDC_SYNC_IN_INTERNAL            1027
#define IDC_SYNC_IN_EXTERNAL            1028
#define IDC_LED_MODE                    1029
#define IDC_FAN_CTRL                    1030
#define IDC_DECODE_POS_Y                1031
#define IDC_DECODE_POS_W                1032
#define IDC_DECODE_POS_H                1033
#define IDC_DEVICE_ID                   1034
#define IDC_DEVICE_VERSION              1035
#define IDC_WRITE2                      1037
#define IDC_BUTTON1                     1039
#define IDC_RESETCAMERA                 1039
#define IDC_STATIC_CAMINFO              1040
#define IDC_STATIC_SERIAL               1041
#define IDC_SPIN_START_FRAME            1042
#define IDC_SPIN_CURRENT_FRAME          1043
#define IDC_SPIN_END_FRAME              1044
#define GROUP_SETTING                   1048
#define IDC_STATIC5                     1049
#define IDC_LABEL_EXPOSE                1049
#define IDC_STATIC6                     1050
#define IDC_STATIC8                     1051
#define IDC_STATIC7                     1052
#define IDC_STATIC9                     1053
#define IDC_STATIC11                    1054
#define IDC_LABEL_SYNC_IN               1054
#define IDC_RESET_SEQNO                 1055
#define IDC_SYNC_IN_SIGNAL_POSI         1056
#define IDC_SYNC_IN_SIGNAL_NEGA         1057
#define IDC_DECODE_CPU                  1058
#define IDC_DECODE_GPU                  1059
#define IDC_STATIC12                    1060
#define IDC_STATIC14                    1061
#define IDC_STATIC15                    1062
#define IDC_LABEL_DELAY                 1062
#define IDC_STATIC16                    1063
#define IDC_STATIC17                    1064
#define IDC_LABEL_WIDTH                 1064
#define IDC_STATIC18                    1065
#define IDC_STATIC19                    1066
#define IDC_LABEL_MAGNIFICATION         1066
#define IDC_STATIC20                    1067
#define IDC_LABEL_QUANTIZATION          1067
#define IDC_STATIC21                    1068
#define IDC_LABEL_DECODE_POSITION       1068
#define IDC_STATIC22                    1069
#define IDC_STATIC23                    1070
#define IDC_STATIC24                    1071
#define IDC_STATIC25                    1072
#define IDC_STATIC27                    1073
#define IDC_LABEL_DECODE_MODE           1073
#define IDC_STATIC13                    1074
#define IDC_LABEL_SYNC_OUT              1074
#define IDC_TEXT_RECORD_TIME            1096
#define IDC_CHECK1                      1100
#define IDC_CHECK_ADVANCED_SETTING      1100
#define IDC_COMBO_RESAVE_FORMAT         1101
#define IDC_TEXT_RESAVE                 1102
#define IDC_LABEL_RESAVE_FORMAT         1102
#define IDC_TEXT_DROP_INTERPOLATE       1103
#define IDC_LABEL_DROP_INTERPOLATE      1103
#define IDC_RADIO_DROP_INTERPOLATE_NON  1104
#define IDC_RADIO_DROP_INTERPOLATE_DARK 1105
#define IDC_RADIO_DROP_INTERPOLATE_PRE  1106
#define IDC_RADIO_DROP_INTERPOLATE_AFTER 1107
#define IDC_PROGRESS_RINGBUFFER         1108
#define IDC_SPIN_RECORDTIME             1119
#define IDC_LABEL_ACQUISITION_MODE      1120
#define IDC_LABEL_RECORD_MODE           1121
#define IDC_LABEL_RECORD_TIME           1122
#define IDC_LABEL_FRAMERATE             1123
#define IDC_LABEL_SHUTTERSPEED          1124
#define IDC_LABEL_SHUTTER_SPEED         1124
#define IDC_LABEL_RESOLUTION            1125
#define IDC_GROUP_FILE_INFO             1126
#define IDC_LABEL_FILE_PATH             1127
#define IDC_LABEL_SIZE                  1128
#define IDC_LABEL_FRAME_COUNT           1129
#define IDC_GROUP_PLAYBACK              1130
#define ID_EDIT_ZOOM_IN                 32771
#define ID_EDIT_ZOOM_OUT                32772
#define ID_EDIT_ZOOM_FIT                32773
#define ID_EDIT_ZOOM_DEFAULT            32774
#define ID_MVERSION_DEVICESETTINGS      32775
#define ID_MVERSION_GRAPH               32776
#define ID_M_DEVICESETTINGS             32777
#define IDD_DEVICESETTINGS              32778
#define ID_M_OUTPUTFRAMEINFO            32779
#define ID_M_HISTGRAM                   32780
#define ID_LANGUAGE_ENGLISH             32781
#define ID_LANGUAGE_JAPANESE            32782

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        337
#define _APS_NEXT_COMMAND_VALUE         32783
#define _APS_NEXT_CONTROL_VALUE         1131
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
