//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// CamMonitor.rc で使用
//
#define IDCANCEL2                       3
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_ERROR_FILEOPEN              101
#define IDS_REC                         102
#define IDS_RECORDING                   103
#define IDS_PLAY                        104
#define IDS_OPEN_FILTER                 105
#define IDS_PAUSE                       106
#define IDS_ALREADY_OPEN                107
#define IDS_RESTART_MSG                 107
#define IDS_ERROR_OPEN                  108
#define IDS_DRAWTEXT_CAMERA             109
#define IDS_ERROR_CODE                  110
#define IDS_IMG_SAVE_COMPLETE           111
#define IDS_SYNC_IN_INTERNAL            111
#define IDS_STOP                        112
#define IDS_CLOSE                       113
#define IDS_SYNC_IN_EXTERNAL            114
#define IDS_DRAWTEXT_FILE               115
#define IDS_QUALITY_NORMAL              116
#define IDS_QUALITY_LOW                 117
#define IDS_QUALITY_HIGH                118
#define IDS_ERROR_OUTPUT_CSV            119
#define IDS_SAVE_CDV_FILTER             120
#define IDS_SAVE_CSV_FILTER             120
#define IDS_COMPLETED                   121
#define IDS_ERROR_SAVE_IMAGE            122
#define IDS_ERROR_SAVE                  122
#define IDR_MAINFRAME                   128
#define IDS_ERROR_NOT_SUPPORTED         129
#define IDD_CAMERA                      310
#define IDD_OPERATION                   312
#define IDD_FILE                        313
#define IDD_SELECT_CAMERA               314
#define IDD_PROGRESS                    316
#define IDD_DEVICE_SETTINGS             322
#define IDD_DIALOG1                     324
#define IDD_LIVE                        328
#define IDD_SAVE_LIVE                   331
#define IDD_SAVE_FILE                   333
#define IDC_ACQUISITION_SINGLE          1001
#define IDC_ACQUISITION_CONTINUOUS      1002
#define IDC_TAB_CTRL                    1002
#define IDC_REFERENCE                   1003
#define IDC_FILEPATH                    1004
#define IDC_SAVE_FILE_RAW               1004
#define IDC_NEXT_FRAME                  1005
#define IDC_FORWARD_FRAME               1005
#define IDC_SAVE_FILE_MULTIPLE_RAW      1005
#define IDC_SAVE_FILE_RAW2              1005
#define IDC_SAVE_FILE_CSV               1005
#define IDC_CURRENT_FRAME               1006
#define IDC_REC                         1006
#define IDC_PLAYBACK                    1007
#define IDC_STOP                        1007
#define IDC_PLAY                        1007
#define IDC_FOLDERPATH                  1008
#define IDC_BACKWARD_FRAME              1008
#define IDC_FILENAME                    1009
#define IDC_GO_TO_START                 1009
#define IDC_FRAMERATE                   1010
#define IDC_GO_TO_END                   1010
#define IDC_START_FRAME                 1011
#define IDC_SHUTTERFPS                  1011
#define IDC_END_FRAME                   1012
#define IDC_RESOLUTION                  1012
#define IDC_OPEN                        1013
#define IDC_SYNC_OUT_DELAY              1013
#define IDC_SLIDER_PLAY                 1014
#define IDC_SYNC_OUT_WIDTH              1014
#define IDC_FRAME_COUNT                 1015
#define IDC_OPENCAMERA                  1015
#define IDC_IMAGE_SIZE                  1016
#define IDC_COMBO_CAMERA                1016
#define IDC_SYNC_OUT_MAGNIFICATION      1016
#define IDC_FILE_FRAMERATE              1017
#define IDC_EDIT_TIMEOUT                1017
#define IDC_EDIT_TRANSFER_TIMEOUT       1017
#define IDC_EDIT_SINGLE_XFER_TIMEOUT    1017
#define IDC_QUANTIZATION                1017
#define IDC_SEQ_NO                      1018
#define IDC_EDIT_STM_COUNT              1018
#define IDC_FOLDERPATH2                 1018
#define IDC_EXPOSE_ON                   1018
#define IDC_EDIT_RING_BUF_COUNT         1018
#define IDC_SPIN_TIMEOUT                1019
#define IDC_FILENAME2                   1019
#define IDC_EXPOSE_OFF                  1019
#define IDC_SPIN_TRANSFER_TIMEOUT       1019
#define IDC_SPIN_SINGLE_XFER_TIMEOUT    1019
#define IDC_SPIN_STM_COUNT              1020
#define IDC_IMG_SAVE                    1020
#define IDC_SPIN_EXPOSE_ON              1020
#define IDC_SPIN_RING_BUF_COUNT         1020
#define IDC_REFERENCE3                  1020
#define IDC_SNAPSHOT                    1020
#define IDC_EDIT_STM_RETRY              1021
#define IDC_REFERENCE2                  1021
#define IDC_SPIN_EXPOSE_OFF             1021
#define IDC_EDIT_STREAMING_TIMEOUT      1021
#define IDC_EDIT_CONTINUOUS_XFER_TIMEOUT 1021
#define IDC_CONFIGURATION               1021
#define IDC_SPIN_STM_RETRY              1022
#define IDC_SAVE_PROGRESS               1022
#define IDC_SPIN_SYNC_OUT_DELAY         1022
#define IDC_PROGRESS_BAR                1022
#define IDC_SPIN_STREAMING_TIMEOUT      1022
#define IDC_SPIN_CONTINUOUS_XFER_TIMEOUT 1022
#define IDC_POST_START_FRAME            1022
#define IDC_ANALYZE_LIVE                1022
#define IDC_PROGRESS_TEXT               1023
#define IDC_SPIN_SYNC_OUT_DELAY2        1023
#define IDC_SPIN_SYNC_OUT_WIDTH         1023
#define IDC_POST_START_FRAME2           1023
#define IDC_POST_END_FRAME              1023
#define IDC_SAVE_TO                     1023
#define IDC_DECODE_POS_X                1024
#define IDC_SAVE_FRAME_INFO             1024
#define IDC_SYNC_OUT_SIGNAL_POSI        1025
#define IDC_ANALYZE_FILE                1025
#define IDC_SYNC_OUT_SIGNAL_NEGA        1026
#define IDC_SAVE_TO_FILE                1026
#define IDC_SYNC_IN_INTERNAL            1027
#define IDC_SYNC_IN_EXTERNAL            1028
#define IDC_LED_MODE                    1029
#define IDC_FAN_CTRL                    1030
#define IDC_DECODE_POS_Y                1031
#define IDC_DECODE_POS_W                1032
#define IDC_DECODE_POS_H                1033
#define IDC_DEVICE_ID                   1034
#define IDC_DEVICE_VERSION              1035
#define IDC_WRITE2                      1037
#define IDC_BUTTON1                     1039
#define IDC_RESETCAMERA                 1039
#define IDC_STATIC_CAMINFO              1040
#define IDC_STATIC_SERIAL               1041
#define IDC_SPIN_START_FRAME            1042
#define IDC_SPIN_CURRENT_FRAME          1043
#define IDC_SPIN_END_FRAME              1044
#define IDC_RESET_SEQNO                 1055
#define IDC_SYNC_IN_SIGNAL_POSI         1056
#define IDC_SYNC_IN_SIGNAL_NEGA         1057
#define ID_EDIT_ZOOM_IN                 32771
#define ID_EDIT_ZOOM_OUT                32772
#define ID_EDIT_ZOOM_FIT                32773
#define ID_EDIT_ZOOM_DEFAULT            32774
#define ID_MVERSION_DEVICESETTINGS      32775
#define ID_MVERSION_GRAPH               32776
#define ID_M_DEVICESETTINGS             32777
#define IDD_DEVICESETTINGS              32778
#define ID_M_OUTPUTFRAMEINFO            32779
#define ID_M_HISTGRAM                   32780

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        335
#define _APS_NEXT_COMMAND_VALUE         32781
#define _APS_NEXT_CONTROL_VALUE         1045
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
